<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>StoreApi.Api</RootNamespace>
    <AssemblyName>StoreApi.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StoreApi.Domain\StoreApi.Domain.csproj" />
    <ProjectReference Include="..\StoreApi.Infrastructure\StoreApi.Infrastructure.csproj" />
  </ItemGroup>
</Project>
